name: testingCI

on:
   push:
    branches: [ main ]
      

jobs: 
  CIWorkFlowTest:
    name: testing
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
